### ISSUE TITLE
Relative/absolute record name conversions

### ISSUE THREAD

**Issue by mholt** [libdns/duckdns#2]
Hi,

Over in the libdns repo, we're discussing standardizing the use of relative or absolute record names in `libdns.Record` structs. The current consensus is that they should be made relative (i.e. for a record named `sub.example.com` in a zone called `example.com`, the name should become `sub`). This may affect your provider implementation.

When you have a chance, would you please check out [this issue](https://github.com/libdns/libdns/issues/12#issuecomment-756135908)? This is the last call for feedback before we decide and I push the changes, and I want to make sure we get it right for the majority of DNS provider implementations so we don't have to change it again.

Link: https://github.com/libdns/libdns/issues/12#issuecomment-756135908

Thank you!

**Comment by francislavoie** [comment]
Pretty sure DuckDNS won't require any changes. :+1:
