### ISSUE TITLE
Issue with last commit

### ISSUE THREAD

**Issue by cameronelliott** [libdns/duckdns#4]
First, thanks to you @francislavoie and Matt for creating this and your hard work doing so.

The last commit https://github.com/libdns/duckdns/commit/56d2fba8f8f3aea089c9abe2df3c20d85362dbf3 to this lib seems to be causing an issue when used with certmagic.

I added some debugging to the latest version to show what's going on:
https://github.com/cameronelliott/duckdns/commit/27ebaf0b4cc53d3303beff7788f01fdb77303ef3

I wrote a simple test-program to create the debug output:
https://github.com/cameronelliott/libdns-issue

Here is the debug output when the test-program is used with `libdns/duckdns` and the extra debugging:
```
c@camerons-mini ~/libdns-issue (master) [1]> go run .
zone duckdns.org.
record.Name _acme-challenge.bug7.duckdns.org
domain _acme-challenge.bug7.duckdns.org.duckdns.org.
olddomain _acme-challenge.bug7.duckdns.org
panic: bug7.duckdns.org: obtaining certificate: [bug7.duckdns.org] Obtain: [bug7.duckdns.org] solving challenges: presenting for challenge: adding temporary record for zone duckdns.org.: DuckDNS request failed, expected (OK) but got (KO), url: [https://www.duckdns.org/update?domains=org.&token=hidden&txt=fhla1fME6WRlHW1mQ0IDVihF0vyPn1U-6TLiO-TblXE&verbose=true], body: KO (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/18469075/5957247) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)

goroutine 1 [running]:
main.checkPanic(...)
	/Users/c/libdns-issue/main.go:14
main.main()
	/Users/c/libdns-issue/main.go:37 +0x23c
exit status 2
c@camerons-mini ~/libdns-issue (master) [1]>
```

I would have proposed a fix, but I don't understand what the objective of the last commit is.
Let me know if I can somehow help.

**Comment by francislavoie** [comment]
`github.com/caddyserver/certmagic v0.12.0` that's the wrong version to require, you need the latest commit of certmagic. Could you try again using the right version of certmagic? Try `go get -d -v github.com/caddyserver/certmagic@7550222c4a6a390cb0b91426d059f1ec5bda59b3`

**Comment by cameronelliott** [comment]
@francislavoie Thank you! Sorry about that! That helped a lot!


But there was still one small issue after that fix.
The domain name after libdns.AbsoluteName() now has a trailing period.
The domain name did not have a trailing period when using the old method: `getDomainFromZoneAndRecord(zone, record)`
The trailing period causes this function to break: `getMainDomain(domain)` called from inside `doRequest()`

When I say break, it returns '.org' which causes an invalid Duckdns request:
```
panic: bug7.duckdns.org: obtaining certificate: [bug7.duckdns.org] Obtain: [bug7.duckdns.org] solving challenges: presenting for challenge: adding temporary record for zone duckdns.org.: DuckDNS request failed, expected (OK) but got (KO), url: [https://www.duckdns.org/update?domains=org.&token=removed&txt=BL03_SOdiYfzoowSAFQefNcNfTNDEEIh5X17ARu0FDk&verbose=true], body: KO (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/18469075/6105011) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)
```

**See the `domains=.org` part of the the query string thats what happens without the fix in the PR I submitted.**

I will submit a very small PR which fixes this issue.

```
# debug output showing the new trailing '.' when using libdns.AbsoluteName()
zone duckdns.org.
record.Name _acme-challenge.bug7
domain _acme-challenge.bug7.duckdns.org.
olddomain _acme-challenge.bug7.duckdns.org
```

**Comment by francislavoie** [comment]
Thanks for the fix!

**Comment by francislavoie** [comment]
I tagged a new release with the fix https://github.com/caddy-dns/duckdns/releases/tag/v0.3.1
